### ISSUE TITLE
Changing how coupons are defined

### ISSUE THREAD

**Issue by AngrySoundTech** [AngrySoundTech/CouponCodes#18]
I'm moving some discussion over here. Following are copies of comments that exist in #3.

**Comment by Drepic26** [comment]
One idea I was tossing around was scrapping different coupon types entirely, and making coupons compound, that is, one coupon could be for multiple things. For example, a coupon for a cookie,  two diamonds and ten xp levels would look like `/coupon add item:cookie;1,diamond;2|xp:10`. This is similar to the format I have in place in my other plugin, [AmpleChatBot](http://dev.bukkit.org/bukkit-plugins/ample-chat-bot/), where the bot can respond with both text and running commands. My only concern with this is that commands would get too complicated, especially after completing #9.

Otherwise, here is a proposed list of coupon type prefixes for this system:

Prefix|Effect
---|---
item:|Gives the player items
xp:|Gives the player xp
econ:|Gives the player economy money(Not yet supported on Canary. See #17)
rank:|Sets the player to a certain rank(Requires Vault on Bukkit)
cmd:|Runs a command as console
pcmd:|Runs a command as player

**Comment by Drepic26** [comment]
Just to put into a little perspective what I said about commands being too complicated if this is done, here's what it would look like if you wanted to create a coupon to give ten levels, 5$, and six enchanted birch planks named Fred with the lore "Delicious".

`/coupon add examplecoupon xp:10|econ:5|item:planks;6;1;{display:{Name:Fred},{Lore:["Delicious"]},{ench:[{id:16,lvl:2}]}}`

Note that this is a somewhat extreme example using minecraft's NBT tag format to add the enchantments and lore to the item, since I have not yet implemented enchants and lore I will most likely have devised an easier way of specifying

**Comment by Sketaful** [comment]
Since you made me jump here, I'll continue my discussion here as well. :)
I like the idea of adding multiple things to a coupon. I do however wonder if it wouldn't be possible to make it so you could do it command by command.

Instead of your way:
"/coupon add examplecoupon xp:10|econ:5|item:planks;6;1;{display:{Name:Fred},{Lore:["Delicious"]},{ench:[{id:16,lvl:2}]}}"

It would help if you did it one command at a time:
/coupon add examplecoupon xp:10
/coupon add examplecoupon econ:5
/coupon add examplecoupon item:planks;6;1;{display:{Name:Fred},{Lore:["Delicious"]},{ench:[{id:16,lvl:2}]}}

Beside making it a little easier adding the things one by one, getting it sorted more in the head as you do it (atleast for me) it fixes the problem that can happen when the max characters in the chat is reached.

**Comment by Drepic26** [comment]
@Sketaful Adding different things in multiple commands seems to be the way to go.

I'll begin mucking around with this after I complete development of and integrate [Drepic26/MultiPluginLib](https://github.com/Drepic26/MultiPluginLib)
